accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import EmailLoginView, FacilitySignUpView, GuardianSignUpView, ChildMyPageView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', EmailLoginView.as_view(), name='login'),
    path('signup/facility/', FacilitySignUpView.as_view(), name='signup_facility'),
    path('signup/guardian/', GuardianSignUpView.as_view(), name='signup_guardian'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("child/mypage/", ChildMyPageView.as_view(), name="child_mypage"),
    path("password/change/", UserPasswordChangeView.as_view(), name="password_change"),
]

boards/urls.py
from django.urls import path
from .views import BoardListView, BoardCreateView ,board_detail

app_name ="boards"

urlpatterns = [
    path("",BoardListView.as_view(),name="list"),
    path("create/", BoardCreateView.as_view(), name="create"),
    path("<int:pk>/", board_detail, name="detail"),
]

dashboard/urls.py
from django.urls import path
from .views import HomeView 

app_name = "dashboard"

urlpatterns = [
    path("",HomeView.as_view(),name="home"),
]

families/urls.py
from django.urls import path
from . import views

app_name = "families"

urlpatterns = [
    path("info/", views.family_info, name="info"),
    path("info/<int:pk>/confirm/", views.family_confirm, name="confirm"),
    path("info/<int:pk>/delete/", views.family_delete, name="delete"),
]

invites/urls.py
from django.urls import path # path("URLの形", 動かすView, name="名前")
from .views import AccountListView, AccountManageView, AccountCreateView

app_name = 'invites'

urlpatterns = [
    path('accounts/', AccountListView.as_view(), name='account_list'), # 一覧画面
    path('accounts/new/', AccountCreateView.as_view(), name='account_new'), # 新規作成画面
    path('accounts/<int:pk>/', AccountManageView.as_view(), name='account_manage'), # 編集画面
]

sodachi_note/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import SodachiPasswordResetView, SodachiPasswordResetConfirmView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls',"accounts"), namespace="accounts")),
    path("accounts/password_reset/", SodachiPasswordResetView.as_view(), name="password_reset"),
    path("accounts/reset/<uidb64>/<token>/",SodachiPasswordResetConfirmView.as_view(),name="password_reset_confirm",),    
    path('accounts/', include('django.contrib.auth.urls')),#ログイン/ログアウト/パスワード再設定
    path("growthlogs/",include(("schoollogs.urls", "schoollogs"),namespace="schoollogs")),
    path("notices/",include(("notices.urls", "notices"), namespace="notices")),
    path("boards/",include(("boards.urls", "boards"), namespace="boards")),
    path("nurseries/", include(("nurseries.urls", "nurseries"), namespace="nurseries")),
    path("families/", include("families.urls")),
    path("invites/", include(("invites.urls", "invites"), namespace="invites")),
    path("attendances/", include(("attendances.urls", "attendances"), namespace="attendances")),
    path('home/', include(("dashboard.urls" , "dashboard"), namespace="dashboard")),
    path('', include(("portfolio.urls" ,"portfolio"), namespace="portfolio")), #トップページ
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang ="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}そだちノート{% endblock %}</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head_extra %}{% endblock %}
</head>

<body>
    {% block header %}
    <header class="site-header">
        <nav class="site-nav">
            <h1 class="logo">
                <a href="{% url 'dashboard:home' %}">そだちノート</a>
            </h1>
            <div class="logout">
                <form action ="{% url 'logout' %}" method="POST" class="logout-form">
                    {% csrf_token %}
                    <button type="submit" class="link-like">
                        <i class="bi bi-box-arrow-right"></i> ログアウト
                    </button>
                </form>             
            </div>
        </nav>
    </header>
    {% endblock %}

    <main class="site-main">
        {% block content %}{% endblock %}
    </main>
    
    {% block footer %}
    <footer class="site-footer">
        <nav class="footer-nav">
            <a class="footer-item" href="{% url 'dashboard:home' %}">
            <i class="bi bi-emoji-smile"></i>
            <span class="label">記録</span>
            </a>

            <a class="footer-item" href="{% url 'notices:list' %}">
            <i class="bi bi-envelope"></i>
            <span>おたより</span>            
            </a>

            <a class="footer-item" href="{% url 'boards:list' %}">
            <i class="bi bi-wechat"></i>
            <span>掲示板</span>
            </a>

            <a class="footer-item"
            href="{% if request.user.role == request.user.Role.FACILITY %}
            {% url 'invites:account_list' %}
            {% else %}
            {% url 'families:info' %}
            {% endif %}">
            <i class="bi bi-people"></i>
            <span>アカウント</span>
            </a>

            
            <a class="footer-item"
                href="{% if request.user.role == request.user.Role.FACILITY %}
                {% url 'nurseries:mypage' %}
                {% else %}
                {% url 'accounts:child_mypage' %}
                {% endif %}">
                <i class="bi bi-person"></i>
                <span>マイページ</span>
            </a>

        </nav>
    </footer>
    {% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}そだちノート{% endblock %}

{% block content %}
            <h1>生活・成長記録</h1>
{% endblock %}